[package]
name = "rust_template"
version = "0.1"
edition = "2022"
description = "Example of Rust GitHub template"
repository = "https://github.com/runtime-machines/rust-template"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
