# Run rustfmt with this config (it should be picked up automatically).
# version = "Two"
# use_small_heuristics = "Max"
# merge_derives = false

# by default we ignore everything in the repository
# tidy only checks files which are not ignored, each entry follows gitignore style
# ignore = []